/*
 * (c) Copyright 2005-2011 JAXIO - Generated by Celerio, a Jaxio tool. http://www.jaxio.com
 */
package com.sun.faces.config;

import javax.el.CompositeELResolver;

import org.springframework.web.jsf.el.SpringBeanFacesELResolver;

/**
 * Resolves MessageSource/ResourceBundle and SpringBeans.
 */
public class ResourceSpringBeanFacesELResolver extends CompositeELResolver {
    public ResourceSpringBeanFacesELResolver() {
        add(new MvcResourceFacesELResolver());
        add(new SpringBeanFacesELResolver());
    }
}